### ISSUE TITLE
ページのコンテンツの文章を100文字取得

### ISSUE THREAD

**Issue by KateSawada** [jphacks/NG_2308#25]
1hやってキツそうだったら諦めよう．タイマーで計っといて!

**Comment by Fuki0612** [comment]
調べたサイト
https://chat.openai.com/
https://www.delftstack.com/ja/howto/javascript/javascript-get-data-from-url/
https://www.delftstack.com/ja/howto/javascript/javascript-get-html-from-url/
https://qiita.com/taishi41228/items/e967d107a79142ade0b6
