### ISSUE TITLE
デフォルトのサウンドを探す

### ISSUE THREAD

**Issue by KateSawada** [jphacks/NG_2308#27]
グッと来る通知音を探す．
探したら，
/src/resources/default_alert.wav として保存．

どこのサイトの素材を持ってきたか，素材ページのURLをREADME.mdの下に
```
## 音声素材
https://なんちゃら.com
```
って追記する．

**Comment by KateSawada** [comment]
まずは，何個か候補を出して，URLを挙げてほしい!
〜18:10

**Comment by Fuki0612** [comment]
キッチンタイマー
https://taira-komori.jpn.org/cooking01.html
時計アラーム
https://otologic.jp/free/se/clock-page02.html

**Comment by Fuki0612** [comment]
プレゼンタイトル表示
https://soundeffect-lab.info/sound/sub-category/business.html
テロレン　にゅぽ　 決定７　決定14　ティロン 
https://mobunikomiudon.com/sound/se-system/
