### ISSUE TITLE
【最後に】動かし方の説明書作る

### ISSUE THREAD

**Issue by KateSawada** [jphacks/NG_2308#52]
環境構築から，ローカルで動かすまでの全部の動作を書いておく．
colabはデモ用，くらいの立ち位置にしておく(無料では30分? しか連続起動できないため)．ローカルマシンとかで動作させるのを推奨，という立ち位置．cudaの導入とかまでは書かなくてOK．

書くべきこと
- chrome拡張の導入
- ローカルのpython環境(3.9.1)
- pip installの注意(最初にpip install --upgrade pipをする&windowsでは最後のを消してpip install)
- src/engine/.envの作成
- 起動すべきプログラムと，その実行ディレクトリ&コマンド

**Comment by KateSawada** [comment]
可能ならmakefileとかあるといい

**Comment by KateSawada** [comment]
README.mdの一番下に書く

**Comment by Lucas544875** [comment]
[documentation/feature/add-useage_#52](https://github.com/jphacks/NG_2308/tree/documentation/feature/add-useage_%2352)
にて作業を行いました。
2つのコミットのうち1つ目のコミット(3e4085a3116c12198314c6d8d0221b56b6ab83d7)のメッセージが誤って #59となっています。内容としてはReadmeの末尾への追記です。
ローカルのLLMの構築方法や、抜けている手順がないか等チェックお願いします
